### ISSUE TITLE
Parameters w\ `param`

### ISSUE THREAD

**Issue by gordio** [srusskih/SublimeJEDI#218]
Parameters autocompletion is very strange. For every parameter it's add 'param'. For example:
```python
def size_fmt(num, suffix='B'):
	for unit in ['', 'Ki', 'Mi', 'Gi', 'Ti', 'Pi', 'Ei', 'Zi']:
		if abs(num) < 1024.0:
			return "%3.1f %s%s" % (num, unit, suffix)
		num /= 1024.0
	return "%.0f %s%s" % (num, 'Yi', suffix)

size_fmt(param num)
```

**Expected:**
`size_fmt(num)`

**Another example:**
```python
def foo(a, b, c, more=False):
	pass

foo(param a, param b, param c)
```

**Comment by srusskih** [comment]
thx. need to look at

**Comment by srusskih** [comment]
What version of sublime text was used?
What version of python was used?

**Comment by gordio** [comment]
Sublime Build: 3142
Python in Sublime: 3.3.6 (default, Feb  2 2017, 05:49:32) 
Python in system: 3.6.2
Jedi last from pip or last from package in Package Control.

**Comment by srusskih** [comment]
thx

**Comment by srusskih** [comment]
@gordio I have pushed fix to master,- please check if it works for you.
If everything is fine, then I'll create a release with the fix.

**Comment by gordio** [comment]
I test #3ebe369 commit, all work fine. Thx.

**Comment by srusskih** [comment]
Always welcome.

**Comment by LynnHo** [comment]
@srusskih When I use package install， the problem still there. (Git is fine)

**Comment by srusskih** [comment]
@LynnHo thanks for feed back. going to bump new version right now (:
